# Generated by Django 5.2.6 on 2025-09-08 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_price', models.IntegerField()),
                ('Products', models.ManyToManyField(to='Main.products')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='Cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Members', to='Main.cart'),
        ),
    ]
