# Generated by Django 5.2.6 on 2025-09-11 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_cart_member_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='Cart',
        ),
        migrations.AddField(
            model_name='cart',
            name='Finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='Member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.member'),
        ),
        migrations.AddField(
            model_name='cart',
            name='Quantity',
            field=models.IntegerField(default=1),
        ),
    ]
